### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by whcmark** [devmark/laravel-angular-cms#1]
## API
- [x] Do not allow to remove owner Role's permission 
- [x] User
- [x] Role
- [ ] Page Database
- [ ] Page API
- [ ] Menu Database
- [ ] Menu API
- [ ] each router check permission 
## Backend
- [x] Dashboard 
- [ ] Page & Menu form
- [x] gulp auto copy files to api public folder
- [x] post category list bad style when length === 0  
- [ ] Refresh token
- [ ] Post can insert media 
- [ ]  Media layout: media category pull left column for user friendly
- [ ] Setting Page
## Frontend
- [ ] Example
- [ ] gulp auto copy files to api public folder
